apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: webtest
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
